get:
  tags:
    - Products
  summary: Lấy danh sách sản phẩm
  description: |-
    API công khai để lấy danh sách sản phẩm, hỗ trợ phân trang, lọc và sắp xếp.
    Tất cả các tham số query đều là tùy chọn.
  operationId: listProducts
  parameters:
    - name: page
      in: query
      description: Số trang (bắt đầu từ 0).
      schema:
        type: integer
        default: 0
    - name: size
      in: query
      description: Số lượng sản phẩm trên mỗi trang.
      schema:
        type: integer
        default: 20
    - name: sort
      in: query
      description: |-
        Tiêu chí sắp xếp.
        Cú pháp: `fieldName,(asc|desc)`.
        Ví dụ: `price,asc` để sắp xếp theo giá tăng dần.
      schema:
        type: string
        example: "price,desc"
    - name: categoryId
      in: query
      description: Lọc sản phẩm theo ID danh mục.
      schema:
        type: string
        format: uuid
    - name: brandId
      in: query
      description: Lọc sản phẩm theo ID thương hiệu.
      schema:
        type: string
        format: uuid
    - name: minPrice
      in: query
      description: Lọc theo giá tối thiểu.
      schema:
        type: number
    - name: maxPrice
      in: query
      description: Lọc theo giá tối đa.
      schema:
        type: number
  responses:
    '200':
      description: Trả về một trang (page) các sản phẩm.
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                type: array
                items:
                  $ref: '../components/schemas/Product.yaml'
              pageable:
                type: object
                properties:
                  pageNumber:
                    type: integer
                  pageSize:
                    type: integer
              totalPages:
                type: integer
              totalElements:
                type: integer